### ISSUE TITLE
Is there no code to extract the mask or I missed it?

### ISSUE THREAD

**Issue by et148** [wtjiang98/BeautyGAN_pytorch#3]

**Comment by wtjiang98** [comment]
The mask file is included in the MT dataset.

**Comment by et148** [comment]
I understand that when training,the image and the corresponding mask are input into the network,but when testing,mask is not required,so we do not need extracting code,right?

**Comment by wtjiang98** [comment]
Yes

**Comment by maarab-sfu** [comment]
Is the mask extracting code available? I want to test it on another dataset.
